# Generated by Django 3.2.19 on 2025-04-11 16:42

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_number', models.CharField(max_length=10, unique=True, validators=[base.models.student_matricule_validator])),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
