# Generated by Django 3.2.19 on 2025-04-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20250411_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.schools'),
        ),
    ]
