# Generated by Django 3.2.19 on 2025-04-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_department_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(limit_choices_to=models.CharField(max_length=50, unique=True), on_delete=django.db.models.deletion.CASCADE, to='base.schools'),
        ),
    ]
