# Generated by Django 3.2.19 on 2025-04-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20250411_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Student',
            new_name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.department'),
            preserve_default=False,
        ),
    ]
