# Generated by Django 3.2.19 on 2025-04-12 09:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_attendance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schools',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='matricule_number',
            field=models.CharField(max_length=10, unique=True, validators=[base.models.lecturer_matricule_validator]),
        ),
    ]
