# Generated by Django 3.2.19 on 2025-04-12 09:12

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_student_matricule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='matricule_number',
            field=models.CharField(max_length=13, unique=True, validators=[base.models.lecturer_matricule_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule_number',
            field=models.CharField(max_length=10, unique=True, validators=[base.models.student_matricule_validator]),
        ),
    ]
