# Generated by Django 3.2.19 on 2025-04-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20250412_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['matricule_number']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['matricule_number']},
        ),
    ]
