# Generated by Django 3.2.19 on 2025-04-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='attendance_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ManyToManyField(to='base.Department'),
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='school',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='school',
            field=models.ManyToManyField(to='base.Schools'),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('qr_code', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.classsession'),
            preserve_default=False,
        ),
    ]
