# Generated by Django 5.2 on 2025-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20250412_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='school',
        ),
    ]
