# Generated by Django 5.2 on 2025-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_lecturer_department_remove_lecturer_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='classsession',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
