# Generated by Django 5.2 on 2025-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_classsession_qr_code_classsession_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
