# Generated by Django 3.2.19 on 2025-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_classsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
