# Generated by Django 3.2.19 on 2025-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_classsession_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
