# Generated by Django 5.2 on 2025-05-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lecturer'),
        ),
    ]
