# Generated by Django 5.2 on 2025-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_classsession_duration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
